name: ${project.name}
main: ${mainClass}
version: ${project.version}
authors: [${project.author}]
commands:
  quest:
    description: Zur Verwendung des Quest-Plugins.
    aliases: 
      - cubequest
      - quests
    usage: /quest
permissions:
  cubequest.use:
    default: true
    description: Erlaubt das Annehmen von Quests.
  cubequest.admin:
    default: op
    description: Erlaubt die Verwaltung des Plugins.
    children:
      cubequest.use: true
softdepend: [Citizens]