name: ${project.name}
main: ${mainClass}
version: ${project.version}
authors: [${project.author}]
commands:
  quest:
    description: Zur Verwendung des Quest-Plugins.
    aliases: cubequest
    usage: /quest
permissions:
  cubequest.admin:
    default: op
    description: Erlaubt die Verwaltung des Plugins.